"use client";
import { useState } from "react";
import type { SlideElement, SlideSpec } from "@/lib/presentation/types";
import SlideCanvas from "./SlideCanvas";
import SlideThumbnail from "./SlideThumbnail";

type Props={slides:SlideSpec[];onChange:(slides:SlideSpec[])=>void};
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;

export default function SlideEditor({slides,onChange}:Props){
 const [current,setCurrent]=useState(0); const [ai,setAi]=useState(""); const [aiLoading,setAiLoading]=useState(false); const [aiError,setAiError]=useState(""); const [saved,setSaved]=useState(false);
 if(!slides.length) return <div className="flex min-h-[500px] items-center justify-center rounded-3xl border border-white/10 bg-white/[.03] text-white/40">No slides yet</div>;
 const slide=slides[current];
 const update=(s:SlideSpec)=>{const next=[...slides];next[current]=s;onChange(next);setSaved(false)};
 function addSlide(){const s:SlideSpec={title:"New slide",subtitle:"Add a clear subtitle",bullets:["Key point","Supporting detail"],visual:"",layout:"focus",purpose:"New idea",elements:[{id:uid("title"),type:"text",x:7,y:8,width:82,height:12,text:"New slide",role:"heading"},{id:uid("body"),type:"text",x:7,y:25,width:70,height:20,text:"Add your content here",role:"body"}]};const next=[...slides,s];onChange(next);setCurrent(next.length-1)}
 function addElement(type:SlideElement["type"]){let el:SlideElement; if(type==="text")el={id:uid("text"),type,x:8,y:70,width:38,height:12,text:"New text",role:"body"}; else if(type==="image")el={id:uid("image"),type,x:55,y:55,width:35,height:30,prompt:"Premium abstract visual",fit:"cover"}; else if(type==="stat")el={id:uid("stat"),type,x:58,y:25,width:25,height:22,value:"42%",label:"Key metric"}; else if(type==="chart")el={id:uid("chart"),type,x:52,y:45,width:40,height:35,kind:"bar",labels:["A","B","C","D"],values:[30,60,45,80],title:"Data"}; else if(type==="table")el={id:uid("table"),type,x:8,y:55,width:45,height:30,columns:["Item","Value"],rows:[["A","72"],["B","54"]]}; else if(type==="diagram")el={id:uid("diagram"),type,x:45,y:25,width:45,height:40,kind:"flow",nodes:[{id:"a",label:"Input"},{id:"b",label:"Process"},{id:"c",label:"Output"}],edges:[{from:"a",to:"b"},{from:"b",to:"c"}]}; else if(type==="cards")el={id:uid("cards"),type,x:7,y:48,width:85,height:35,items:[{title:"Point 1",body:"Explain the idea"},{title:"Point 2",body:"Explain the value"},{title:"Point 3",body:"Explain the result"}]}; else if(type==="comparison")el={id:uid("comparison"),type,x:8,y:35,width:84,height:45,leftTitle:"Option A",rightTitle:"Option B",rows:[{label:"Speed",left:"Fast",right:"Medium"},{label:"Cost",left:"Low",right:"High"}]}; else if(type==="process")el={id:uid("process"),type,x:8,y:55,width:84,height:28,steps:[{title:"Discover"},{title:"Build"},{title:"Launch"}]}; else if(type==="roadmap")el={id:uid("roadmap"),type,x:8,y:48,width:84,height:35,phases:[{title:"Now",items:["Foundation"]},{title:"Next",items:["Scale"]},{title:"Later",items:["Expand"]}]}; else if(type==="timeline")el={id:uid("timeline"),type,x:8,y:50,width:84,height:32,items:[{date:"01",title:"Start"},{date:"02",title:"Milestone"},{date:"03",title:"Outcome"}]}; else if(type==="quote")el={id:uid("quote"),type,x:12,y:35,width:70,height:30,quote:"A strong idea deserves a clear story.",author:"SlideForge"}; else el={id:uid("shape"),type:"shape",x:70,y:65,width:18,height:18,shape:"circle"}; update({...slide,elements:[...slide.elements,el]}); }
 async function runAI(){if(!ai.trim()||aiLoading)return;setAiLoading(true);setAiError("");try{const r=await fetch("/api/edit-slide",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({instruction:ai.trim(),slide})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"AI edit failed");if(!d.slide)throw new Error("AI returned no slide");update(d.slide);setAi("")}catch(e){setAiError(e instanceof Error?e.message:"AI edit failed")}finally{setAiLoading(false)}}
 function save(){try{localStorage.setItem("slideforge-presentation",JSON.stringify(slides));setSaved(true);setTimeout(()=>setSaved(false),1500)}catch{setSaved(false)}}
 function move(dir:number){const n=current+dir;if(n<0||n>=slides.length)return;const next=[...slides];[next[current],next[n]]=[next[n],next[current]];onChange(next);setCurrent(n)}
 function remove(){if(slides.length<=1)return;const next=slides.filter((_,i)=>i!==current);onChange(next);setCurrent(Math.min(current,next.length-1))}
 return <div className="overflow-hidden rounded-3xl border border-white/10 bg-black/20 shadow-2xl backdrop-blur-xl">
  <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 p-4"><div><div className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-300/70">AI Presentation Studio</div><div className="mt-1 text-sm text-white/50">Slide {current+1} / {slides.length}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>move(-1)} className="rounded-xl border border-white/10 px-3 py-2 text-xs">←</button><button onClick={()=>move(1)} className="rounded-xl border border-white/10 px-3 py-2 text-xs">→</button><button onClick={remove} className="rounded-xl border border-red-400/10 px-3 py-2 text-xs text-red-300">Delete</button><button onClick={save} className="rounded-xl bg-white px-4 py-2 text-xs font-semibold text-black">{saved?"Saved ✓":"Save"}</button></div></div>
  <div className="grid lg:grid-cols-[210px_minmax(0,1fr)_290px]">
   <aside className="border-b border-white/10 p-3 lg:border-b-0 lg:border-r"><div className="mb-3 flex justify-between text-[10px] uppercase tracking-widest text-white/30"><span>Slides</span><span>{slides.length}</span></div><div className="grid grid-cols-2 gap-2 lg:grid-cols-1">{slides.map((s,i)=><SlideThumbnail key={s.title+ i} slide={s} index={i} active={i===current} onClick={()=>setCurrent(i)}/>)}<button onClick={addSlide} className="aspect-video rounded-xl border border-dashed border-white/15 text-xs text-white/35">+ Add slide</button></div></aside>
   <main className="min-w-0 p-4 sm:p-6 lg:p-8"><SlideCanvas slide={slide} onChange={update}/><div className="mt-3 flex flex-wrap gap-2 rounded-2xl border border-white/10 bg-white/[.025] p-3"><span className="mr-2 self-center text-[9px] uppercase tracking-widest text-white/25">Add</span>{(["text","image","stat","chart","table","diagram","cards","comparison","process","roadmap","timeline","quote"] as const).map(t=><button key={t} onClick={()=>addElement(t)} className="rounded-lg border border-white/10 px-2.5 py-1.5 text-[10px] text-white/55 hover:bg-white/10 hover:text-white">{t}</button>)}</div></main>
   <aside className="border-t border-white/10 p-4 lg:border-l lg:border-t-0"><div className="mb-3 text-[10px] font-semibold uppercase tracking-[.18em] text-violet-300">AI Assistant</div><div className="mb-3 flex flex-wrap gap-2">{["Make it more persuasive","Make it concise","Add a chart","Create a timeline","Rewrite for investors"].map(x=><button key={x} onClick={()=>setAi(x)} className="rounded-full border border-white/10 px-2.5 py-1.5 text-[9px] text-white/45 hover:bg-white/10 hover:text-white">{x}</button>)}</div><textarea value={ai} onChange={e=>setAi(e.target.value)} placeholder="Tell SlideForge how to improve this slide…" className="min-h-[150px] w-full resize-none rounded-2xl border border-white/10 bg-black/30 p-3 text-sm text-white outline-none placeholder:text-white/20 focus:border-violet-400/40"/><button disabled={!ai.trim()||aiLoading} onClick={runAI} className="mt-2 w-full rounded-xl bg-gradient-to-r from-violet-500 to-cyan-400 px-4 py-3 text-xs font-bold text-white disabled:opacity-40">{aiLoading?"Thinking…":"Apply with AI"}</button>{aiError&&<p className="mt-3 text-xs text-red-300">{aiError}</p>}<div className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-3 text-[10px] leading-5 text-white/35">AI edits the structured slide itself — text, visuals, layout and presentation elements — instead of returning a chat-only answer.</div></aside>
  </div>
 </div>
}
